-- phpMyAdmin SQL Dump
-- Generated by RiskRadar dump_schema.py
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 13, 2026 at 04:49 PM UTC
-- Server version: 10.4.32-MariaDB
--

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `riskradar_db`
--

SET FOREIGN_KEY_CHECKS=0;

-- --------------------------------------------------------

--
-- Table structure for table `alert_raw_payloads`
--

DROP TABLE IF EXISTS `alert_raw_payloads`;
CREATE TABLE `alert_raw_payloads` (
  `alert_id` int(11) NOT NULL,
  `raw_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`raw_payload`)),
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`alert_id`),
  CONSTRAINT `alert_raw_payloads_ibfk_1` FOREIGN KEY (`alert_id`) REFERENCES `alerts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `alerts`
--

DROP TABLE IF EXISTS `alerts`;
CREATE TABLE `alerts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source` varchar(100) NOT NULL,
  `source_id` text DEFAULT NULL,
  `alert_type` varchar(100) NOT NULL,
  `severity` varchar(50) NOT NULL,
  `title` text NOT NULL,
  `description` text DEFAULT NULL,
  `raw_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_data`)),
  `location_id` int(11) DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `location_name` text DEFAULT NULL,
  `event_start` text DEFAULT NULL,
  `event_end` text DEFAULT NULL,
  `fetched_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_source_alert` (`source`,`source_id`) USING HASH,
  KEY `location_id` (`location_id`),
  KEY `idx_alerts_source_fetched_at` (`source`,`fetched_at`),
  KEY `idx_alerts_type_severity_fetched_at` (`alert_type`,`severity`,`fetched_at`),
  CONSTRAINT `alerts_ibfk_1` FOREIGN KEY (`location_id`) REFERENCES `locations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `alerts_archive`
--

DROP TABLE IF EXISTS `alerts_archive`;
CREATE TABLE `alerts_archive` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_id` int(11) NOT NULL,
  `source` text NOT NULL,
  `source_id` text DEFAULT NULL,
  `alert_type` text NOT NULL,
  `severity` text NOT NULL,
  `title` text NOT NULL,
  `description` text DEFAULT NULL,
  `raw_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_data`)),
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `location_name` text DEFAULT NULL,
  `event_start` text DEFAULT NULL,
  `event_end` text DEFAULT NULL,
  `fetched_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `archived_at` datetime NOT NULL,
  `cleanup_run_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `original_id` (`original_id`),
  KEY `cleanup_run_id` (`cleanup_run_id`),
  CONSTRAINT `alerts_archive_ibfk_1` FOREIGN KEY (`cleanup_run_id`) REFERENCES `cleanup_runs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `cleanup_runs`
--

DROP TABLE IF EXISTS `cleanup_runs`;
CREATE TABLE `cleanup_runs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `table_name` text NOT NULL,
  `schedule_kind` text NOT NULL,
  `cutoff_at` datetime NOT NULL,
  `rows_eligible` int(11) NOT NULL,
  `rows_archived` int(11) NOT NULL,
  `rows_deleted` int(11) NOT NULL,
  `storage_bytes_estimated` int(11) NOT NULL,
  `duration_ms` int(11) NOT NULL,
  `dry_run` int(11) NOT NULL,
  `status` varchar(50) NOT NULL,
  `error_message` text DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `completed_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cleanup_runs_status_started_at` (`status`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `locations`
--

DROP TABLE IF EXISTS `locations`;
CREATE TABLE `locations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `latitude` float NOT NULL,
  `longitude` float NOT NULL,
  `location_name` text NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_locations_lat_lon_name` (`latitude`,`longitude`,`location_name`) USING HASH,
  KEY `idx_locations_lat_lon` (`latitude`,`longitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migration_log`
--

DROP TABLE IF EXISTS `migration_log`;
CREATE TABLE `migration_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp` datetime NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `action` text DEFAULT NULL,
  `status` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notification_dispatch_log`
--

DROP TABLE IF EXISTS `notification_dispatch_log`;
CREATE TABLE `notification_dispatch_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `alert_id` int(11) NOT NULL,
  `initiated_by_user_id` int(11) NOT NULL,
  `provider` text NOT NULL,
  `recipients_total` int(11) NOT NULL,
  `sent_count` int(11) NOT NULL,
  `failed_count` int(11) NOT NULL,
  `status` varchar(50) NOT NULL,
  `error_message` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `alert_id` (`alert_id`),
  KEY `idx_notification_dispatch_initiated_by_user_id` (`initiated_by_user_id`),
  KEY `idx_notification_dispatch_status_created_at` (`status`,`created_at`),
  CONSTRAINT `notification_dispatch_log_ibfk_1` FOREIGN KEY (`alert_id`) REFERENCES `alerts` (`id`),
  CONSTRAINT `notification_dispatch_log_ibfk_2` FOREIGN KEY (`initiated_by_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `scrape_log`
--

DROP TABLE IF EXISTS `scrape_log`;
CREATE TABLE `scrape_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source` varchar(100) NOT NULL,
  `status` varchar(50) NOT NULL,
  `alerts_fetched` int(11) DEFAULT NULL,
  `alerts_new` int(11) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `duration_ms` int(11) DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `completed_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_scrape_log_source_started_at` (`source`,`started_at`),
  KEY `idx_scrape_log_status_completed_at` (`status`,`completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `scrape_log_archive`
--

DROP TABLE IF EXISTS `scrape_log_archive`;
CREATE TABLE `scrape_log_archive` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_id` int(11) NOT NULL,
  `source` text NOT NULL,
  `status` text NOT NULL,
  `alerts_fetched` int(11) DEFAULT NULL,
  `alerts_new` int(11) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `duration_ms` int(11) DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `completed_at` datetime NOT NULL,
  `archived_at` datetime NOT NULL,
  `cleanup_run_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `original_id` (`original_id`),
  KEY `cleanup_run_id` (`cleanup_run_id`),
  CONSTRAINT `scrape_log_archive_ibfk_1` FOREIGN KEY (`cleanup_run_id`) REFERENCES `cleanup_runs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `summaries`
--

DROP TABLE IF EXISTS `summaries`;
CREATE TABLE `summaries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `content` text NOT NULL,
  `summary_type` varchar(50) NOT NULL,
  `alert_ids` text DEFAULT NULL,
  `region` text DEFAULT NULL,
  `generated_at` datetime NOT NULL,
  `model_used` text DEFAULT NULL,
  `token_count` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_summaries_summary_type_generated_at` (`summary_type`,`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `summaries_archive`
--

DROP TABLE IF EXISTS `summaries_archive`;
CREATE TABLE `summaries_archive` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_id` int(11) NOT NULL,
  `title` text NOT NULL,
  `content` text NOT NULL,
  `summary_type` text NOT NULL,
  `alert_ids` text DEFAULT NULL,
  `region` text DEFAULT NULL,
  `generated_at` datetime NOT NULL,
  `model_used` text DEFAULT NULL,
  `token_count` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `archived_at` datetime NOT NULL,
  `cleanup_run_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `original_id` (`original_id`),
  KEY `cleanup_run_id` (`cleanup_run_id`),
  CONSTRAINT `summaries_archive_ibfk_1` FOREIGN KEY (`cleanup_run_id`) REFERENCES `cleanup_runs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `summary_alerts`
--

DROP TABLE IF EXISTS `summary_alerts`;
CREATE TABLE `summary_alerts` (
  `summary_id` int(11) NOT NULL,
  `alert_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`summary_id`,`alert_id`),
  KEY `idx_summary_alerts_alert_id` (`alert_id`),
  CONSTRAINT `summary_alerts_ibfk_1` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `summary_alerts_ibfk_2` FOREIGN KEY (`alert_id`) REFERENCES `alerts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `user_alert_type_preferences`
--

DROP TABLE IF EXISTS `user_alert_type_preferences`;
CREATE TABLE `user_alert_type_preferences` (
  `user_id` int(11) NOT NULL,
  `alert_type` varchar(64) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`user_id`,`alert_type`),
  KEY `idx_user_alert_type_preferences_alert_type` (`alert_type`),
  CONSTRAINT `user_alert_type_preferences_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_token` text DEFAULT NULL,
  `display_name` text DEFAULT NULL,
  `email` text DEFAULT NULL,
  `email_encrypted` text DEFAULT NULL,
  `email_hmac` varchar(64) DEFAULT NULL,
  `password_hash` text DEFAULT NULL,
  `zip_code` text DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `alert_types` text DEFAULT NULL,
  `notify_severity` text DEFAULT NULL,
  `notify_push` tinyint(1) NOT NULL,
  `notify_email` tinyint(1) NOT NULL,
  `notify_sms` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_hmac` (`email_hmac`),
  UNIQUE KEY `email` (`email`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `zip_geo`
--

DROP TABLE IF EXISTS `zip_geo`;
CREATE TABLE `zip_geo` (
  `zip_code` varchar(10) NOT NULL,
  `latitude` float NOT NULL,
  `longitude` float NOT NULL,
  `state` varchar(8) DEFAULT NULL,
  `city` varchar(128) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`zip_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS=1;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;